license="${mod_license}"

[[mods]]
modId="${fixture_mod_id}"
version="${mod_version}"
displayName="${fixture_mod_name}"
description='''
${fixture_mod_description}
'''

[[dependencies.${fixture_mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${fixture_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
