license="${mod_license}"

[[mods]]
modId="${admin_bridge_mod_id}"
version="${mod_version}"
displayName="${admin_bridge_mod_name}"
description='''
${admin_bridge_mod_description}
'''

[[dependencies.${admin_bridge_mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.${admin_bridge_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
